#!/bin/sh
set -eu

url="${1:?public URL is required}"
expected_release="${2:?expected release is required}"
printf '%s %s\n' "$url" "$expected_release" >>"${FAKE_SMOKE_LOG:?}"
"${ORACLE_INFRA_CURL_BIN:-curl}" --fail --silent --show-error --location --max-time 30 "$url" >/dev/null
test "$(cat "${FAKE_RUNNING_RELEASE_FILE:?}")" = "$expected_release"
